### ISSUE TITLE
Where to get sources of accessibility forwarder?

### ISSUE THREAD

**Issue by ex3ndr** [google-deepmind/android_env#224]
It seems that sources of APK are missing, is it opensource?

**Comment by kenjitoyama** [comment]
Hello @ex3ndr, the AccessibilityForwarder app is not open source yet, but we will work on it. There's no fundamental blocker, but we need to find someone with the time to do it and to iron out the details, especially around building it with open source tools (e.g. Bazel) instead of our internal build system (Blaze). @crawles is interested in getting it out because it's a critical component of https://github.com/google-research/android_world.

I'll leave this issue open to track its progress. Cheers.

**Comment by ex3ndr** [comment]
Thanks! This would be insanely useful: i am trying to reimplement it (with slightly different networking) and normal usage of accessibility often misses some windows on some android versions and it would be very helpful to see how you guys achieved this.

**Comment by kenjitoyama** [comment]
Please see the newly added `apps/` folder from PR #232. Cheers!
